### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by OtariOboladzeSfC** [ZachGoldberg/Startup-CTO-Handbook#2]
Under [TWO TYPES OF DECISIONS](https://github.com/ZachGoldberg/Startup-CTO-Handbook/blob/main/StartupCTOHandbook.md#-two-types-of-decisions) there is " ey " instead of "It"? not sure. Just search " ey " with trailing spaces and it shows up

**Comment by ZachGoldberg** [comment]
Thanks, fixed in 11 places!  During the .doc -> .md conversion some funny things happened to `Th` -- all the `The` and `This` and  `They` etc became `e`, `is` and `ey`... fixing 'em as I find them!  Feel free to let me know if you find others.

**Comment by OtariOboladzeSfC** [comment]
maybe one more? [PEOPLE-PUZZLE SOLVER](https://github.com/ZachGoldberg/Startup-CTO-Handbook/blob/main/StartupCTOHandbook.md#people-puzzle-solver) the end sentence at "people-puzzle solver" needs something

**Comment by p2edwards** [comment]
@ZachGoldberg I'm reading a few "Thee"'s where it should read "The". Ctrl+F "Thee" to find them.

**Comment by ZachGoldberg** [comment]
Thanks @p2edwards, just corrected those as well

**Comment by p2edwards** [comment]
@ZachGoldberg  Found another: 

- isn t" -> "isn't"

The italicized Max Mintz quote [here](https://github.com/ZachGoldberg/Startup-CTO-Handbook/blob/485c2ffb0b00463b3f88013812c3ecde9f3c0e7f/StartupCTOHandbook.md?plain=1#L130-L132) could maybe be a quote block (`> `)

**Comment by p2edwards** [comment]
- Sometimes ". at" -> ". That". (case sensitive)

**Comment by ZachGoldberg** [comment]
Fixing typos in a markdown document is way easier than most bug tickets I've done. isn't and that fixed!

**Comment by p2edwards** [comment]
- Some contractions/possessives:
  -  "couldn t"
  - "I d " / "He d " (trailing space)
  - "Einstein s "
- [Date range](https://github.com/ZachGoldberg/Startup-CTO-Handbook/blob/cbe5e7171efacecfecf6d920754c90e075729120/StartupCTOHandbook.md?plain=1#L132) could use an en dash (—)

**Comment by p2edwards** [comment]
- " s " for more possessives

**Comment by ZachGoldberg** [comment]
> * " s " -> "'s " — more possessives
>   
>   * also with t, d, ll...?
> * ". is is " -> ". This is "
> * "] is is " -> "] This is "
> * "] e " -> "] The "
> * ". ese " -> ". These "
> * ". us " -> ". Thus "
> * ". ough " -> ". Though "
>   
>   * Maybe a search for ". Th"  in the original doc might turn up more examples?
>   * Getting ings Done — great book
> 
> As an aside, I'm curious if these are happening due to an unrecognized ["Th" ligature](https://commons.m.wikimedia.org/wiki/Category:Ligature_%22Th%22) somewhere in the conversion pipeline.
> 
> Maybe using a different font in the source doc (one with no ligatures at all), and converting all smart quote marks to ASCII, etc, en and em dashes to sets of hyphens — could result in a cleaner Markdown export?
> 
> Could be easier than spot checking for the rest of the missing quotes / chopped words.
> 
> On the other hand, the crowdsourced copy editing is probably more fun 😅

Eh, idk about fun, definitely some sunk-cost fallacy now that I've put a few hours into fixing up the auto-converted doc and I've got the inertia though. I suppose most authors, upon first publishing their book, don't go to the editor and say "please make this in markdown so I can post it on GitHub" so I'm not surprised by the rough edges ;)
