### ISSUE TITLE
Audio book version

### ISSUE THREAD

**Issue by BigBerny** [ZachGoldberg/Startup-CTO-Handbook#28]
Hi Zach
I have just read the first quarter yet but I really like it. Since I prefer audio books though to listen while computing, I created one with OpenAI tts-1-hd. I had to split the file in chunks and merge it but the end product sounds quite nice. Just listened to the first few minutes. I could upload it here if you want but wanted to ask first. As you also sell the book on Amazon it would also be understandable if you don't want that. Just let me know.

It's an AAC with 207 MB (64kbit/s mono).

Best
Berny

**Comment by ZachGoldberg** [comment]
Hey Berny - that's super cool!  I'd be very curious how the AI generated version sounds.  I'm actually near the finish line on publishing an audiobook version that I narrated, that should be available on audible in the next month or so.  I'd be happy to host an AI-version for free here on GitHub though in parallel!

**Comment by BigBerny** [comment]
Cool 👍
I cannot upload the file here but you can download it and then host it wherever you want: https://drive.google.com/file/d/1IN3EKoHRTBSws-hkwPJtfhl1ALS8Zkh0/view?usp=sharing

**Comment by BigBerny** [comment]
If you manage to release it on Audible before I finish listening to it, I'll also buy it 😄

**Comment by ZachGoldberg** [comment]
Just heard from my editor, the book will be uploaded to audible by 3/1. They have a review process, so the expectation is its live to the public around 3/15/2024!

**Comment by ZachGoldberg** [comment]
The audiobook was published today on [Audible](https://www.audible.com/pd/B0CXB5YZL2)!
